function(make_test name)
  add_executable(test_${name} test_${name}.cc)
  target_include_directories(test_${name} PUBLIC ${INC_DIR})
  target_link_libraries(test_${name} PUBLIC ccmqsrv event nlohmann_json::nlohmann_json uuid)
  add_test(NAME ${name} COMMAND test_${name})
endfunction()

make_test(base)
make_test(socket)
make_test(rpc_server)
make_test(rpc_client)
make_test(parse)
make_test(rpc_utils)
make_test(server)
make_test(tem)
make_test(event)
make_test(uuid)
make_test(class_matryoshka_doll)
make_test(res_event)
make_test(client)
make_test(thread_detach)
make_test(client_event)
make_test(async_call)
